# Generated by Django 5.1 on 2025-02-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('eligibility_criteria', models.TextField()),
                ('gpa_requirement', models.FloatField(blank=True, null=True)),
                ('income_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('age_limit', models.IntegerField(blank=True, null=True)),
                ('available_for_courses', models.CharField(help_text='Comma-separated list of courses', max_length=255)),
                ('deadline', models.DateField()),
            ],
        ),
    ]
